### ISSUE TITLE
When deploying and the snap is not available in /tmp/slurm.snap adding a unit fails

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/slurm-charms#33]
So, the slurm stack is deployed in vsphere:

Then I did:

juju add-machine --constraints "mem=32G cores=8"
added machine 7
juju add-unit compute --to 7

.... then the install hook failes with the below error:

```
unit-compute-2: 11:08:20 ERROR unit.compute/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 100, in <module>
    main(SlurmdCharm)
  File "/var/lib/juju/agents/unit-compute-2/charm/venv/ops/main.py", line 398, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-compute-2/charm/venv/ops/framework.py", line 638, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-compute-2/charm/venv/ops/framework.py", line 673, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 54, in _on_install
    self.slurm_manager.install()
  File "/var/lib/juju/agents/unit-compute-2/charm/venv/slurm_ops_manager/slurm_ops.py", line 120, in install
    self._slurm_resource_manager.setup_system()
  File "/var/lib/juju/agents/unit-compute-2/charm/venv/slurm_ops_manager/slurm_snap_manager.py", line 162, in setup_system
    resource_size = Path(self._resource_path).stat().st_size
  File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/slurm.snap'
unit-compute-2: 11:08:20 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-compute-2: 11:08:20 DEBUG juju.machinelock machine lock released for uniter (run install hook)

```

**Comment by jamesbeedy** [comment]
@erik78se thanks for reporting this. I don't see this issue popping up anywhere so I'm going to close this out. Please reopen if this pops up again.
